import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend_deca",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Catur Insan Cendekia University Cirebon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lexendDeca.className}`}>
      <body className={`${lexendDeca.variable} antialiased`}>{children}</body>
    </html>
  );
}
